-- MySQL Script generated by MySQL Workbench
-- Sun Jun 21 19:45:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- para ver as alteraões abra uma query e use: 
-- USE SOPIE;
-- SELECT * FROM Projeto;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SOPIE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SOPIE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOPIE` DEFAULT CHARACTER SET utf8 ;
USE `SOPIE` ;

-- -----------------------------------------------------
-- Table `SOPIE`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOPIE`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `registroprofessor` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  `senhahash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOPIE`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOPIE`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `alunolider` VARCHAR(100) NOT NULL,
  `grupo` MEDIUMTEXT NOT NULL,
  `orientador` VARCHAR(100) NULL,
  `descricao` LONGTEXT NOT NULL,
  PRIMARY KEY (`idProjeto`),
  UNIQUE INDEX `idProjeto_UNIQUE` (`idProjeto` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE SOPIE;

ALTER TABLE Projeto 
ADD COLUMN professor VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
USE SOPIE;
SELECT * FROM Projeto;